server.port=8182

spring.application.name=invogent

spring.datasource.url=jdbc:postgresql://db.jwhedgpmyypnwjddhdfr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Tuntun@957279
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect